# Base StayBook : les manifests communs à tous les environnements.
# Pas de namespace ici : c'est l'overlay qui le fixe.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 10-postgres-hotels.yaml
  - 11-postgres-reservations.yaml
  - 20-hotels-service.yaml
  - 21-reservations-service.yaml
  - 30-gateway.yaml
  - 40-front.yaml
