# StayBook prod : overlays/prod, namespace staybook-prod. Mis à jour par une promotion manuelle (pull request).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staybook-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io   # supprimer l'Application supprime aussi ses ressources
spec:
  project: staybook-prod
  source:
    repoURL: https://github.com/<VOTRE-LOGIN>/staybook-gitops.git   # À COMPLÉTER
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: staybook-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
